### ISSUE TITLE
No languages in selector available

### ISSUE THREAD

**Issue by AstCommodore** [CodersCare/localizer#1]
He folks!

I've set up a clean TYPO3 v10 by DDEV / composer, imported a customer DB from a v11 system and set up the site configuration and language sections.

Follow up the documentation of localizer ends up in an empty languages dropdown in Localizer Selector -> Select a cart -> Languages

What did I do wrong? The documentation remain silent ...

Greetings
André

**Comment by Bunnyfield** [comment]
Reading `TYPO3 v10` together with `customer DB from a v11` feels wrong, because there have been several changes between CMS 10 and 11 especially regarding language handling. Is there a specific reason why you are trying it this way?

If it's a kind of a workaround because there is no public version of localizer which is compatible with CMS 11 yet, I would recommend to support our crowd funding campaign, which will give you immediate access to L10nmgr 11-dev and Localizer 11-dev, which are both compatible to both CMS 10 and 11.

https://coders.care/for/crowdfunding/l10nmgr-and-localizer/support
